// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYiWAZJcWd8cXLjL0jAb5IYzSc9fWmCQE',
    appId: '1:439316506505:web:f7ae312a3310d7d9212358',
    messagingSenderId: '439316506505',
    projectId: 'minito-4c78a',
    authDomain: 'minito-4c78a.firebaseapp.com',
    storageBucket: 'minito-4c78a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgCw27Mr4Jc3asuH7yRhNP7Ib7f8W-cH8',
    appId: '1:439316506505:android:9143dc634fa7e05c212358',
    messagingSenderId: '439316506505',
    projectId: 'minito-4c78a',
    storageBucket: 'minito-4c78a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Brxp2KMncXNRv-qGGR8aEognAJYlaFA',
    appId: '1:439316506505:ios:348d147276a77f75212358',
    messagingSenderId: '439316506505',
    projectId: 'minito-4c78a',
    storageBucket: 'minito-4c78a.firebasestorage.app',
    iosBundleId: 'com.bayuotech.minito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Brxp2KMncXNRv-qGGR8aEognAJYlaFA',
    appId: '1:439316506505:ios:753c38721382a931212358',
    messagingSenderId: '439316506505',
    projectId: 'minito-4c78a',
    storageBucket: 'minito-4c78a.firebasestorage.app',
    iosBundleId: 'com.example.minito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYiWAZJcWd8cXLjL0jAb5IYzSc9fWmCQE',
    appId: '1:439316506505:web:637f1755d4b1f724212358',
    messagingSenderId: '439316506505',
    projectId: 'minito-4c78a',
    authDomain: 'minito-4c78a.firebaseapp.com',
    storageBucket: 'minito-4c78a.firebasestorage.app',
  );
}
